spring.application.name=order-inventory

spring.datasource.url=${postgresql://postgres.zkdqiiykfrqfndyjnzsy:MTk8JSwGwIBR88Qt@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
}
spring.datasource.username=${postgres.zkdqiiykfrqfndyjnzsy}
spring.datasource.password=${MTk8JSwGwIBR88Qt}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

